spring.application.name=ligasync-backend

# CONFIGURACIÓN DE LA BASE DE DATOS (Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

#SPRING DATA JPA (Crea la tabla automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PUERTO
server.port=8080

# CONFIGURACIÓN DE CORREO (GMAIL SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# CONFIGURACIÓN DE STRIPE
stripe.api.key=${STRIPE_API_KEY}
frontend.url=${FRONTEND_URL:http://localhost:4200}